name: Test

on:
  push:
    branches:
      - master

jobs:
  coverage-testing:
    runs-on: ubuntu-latest
    name: test
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install and Test
        run: |
          npm install
          npm run test

      - name: codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
